name: Build and test
on: [pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Google benchmark
        run: sudo apt-get install -y libbenchmark-dev
      - name: Run CMake
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug
      - name: Build project
        run: cd build && make
      - name: Test
        run: cd build && ./bench
